### ISSUE TITLE
Issue installing from Git using pip

### ISSUE THREAD

**Issue by adambirds** [zulip/zulint#24]
I keep getting this issue when installing from pip, trying multiple Ubuntu machines and python venvs. I get this error:

```
ERROR: Command errored out with exit status 1:
   command: /project/zulinttest/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k5nb2u_7/zulint/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k5nb2u_7/zulint/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1eim5wzx
       cwd: /tmp/pip-install-k5nb2u_7/zulint/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for zulint
  Running setup.py clean for zulint
Failed to build zulint
```

If I try it again after doing `pip install wheel` it works fine. I also tried in my fork setting wheel as required, but this still causes the error. But as wheel did get installed it succeeds the second time of running.

This is being tried in a requirements.txt file using `pip3 install -r requirements.txt`

**Comment by andersk** [comment]
This is not a fatal error. After printing this message, `pip` falls back on `setup.py install` and the installation succeeds anyway.

The current version of `pip` no longer prints this spurious error and instead shows a much quieter and clearer message:

```
Using legacy 'setup.py install' for zulint, since package 'wheel' is not installed.
```

[chat.zulip.org discussion](https://chat.zulip.org/#narrow/stream/9-issues/topic/zulint.20install.20issues/near/1334045)
